title: The Starry-Eyed Investor

description: "A value investing strategy that uses existing, independent, and trustworthy research in a simple, repeatable, automated process."

sass:
    sass_dir: assets/bootstrap/scss

# uninstalled jekyll-admin
# rack, rack-protection, sinatra, multi_json, backports, sinatra-contrib, jekyll-admin
# these were installed with jekyll-admin